version: 2.1
orbs:
  architect: giantswarm/architect@8.2.2

workflows:
  build:
    jobs:
      - architect/go-build:
          binary: gitrepo-version
          architectures: "linux/amd64,linux/arm64"
